image: kozora/python3-nodejs:latest

stages:
  - update

update:
  stage: update
  tags:
    - local
  only:
    - master
  before_script:
    - pip install -U pip setuptools
    - pip install hererocks
    - hererocks lua_install -r^ --lua=5.3
    - export PATH=$PATH:$PWD/lua_install/bin
    - node -v
    - python -V
    - pip --version
    - pip install -r requirements.txt
  script:
    - python LuatableBot.py
