stages:
  - kcwiki-luatable
    
kcwiki-luatable:
  stage: kcwiki-luatable

  tags:
    - shell
  script:
    - rsync -avzP ./ /home/gitlab-runner/kcwiki-luatable
    - cd /home/gitlab-runner/kcwiki-luatable
    - docker build -t kcwiki-luatable .
    - docker run --env-file .env -t kcwiki-luatable