image: python:3

stages:
  - make_update

cache:
  paths:
    - cache
  key: $CI_PROJECT_ID

make_update:
  stage: make_update
  tags:
    - hn-i7
  only:
    - master
  variables:
    LUA: lua=5.3
  before_script:
    - apt-get update
    - apt-get install -y -qq unzip
    - pip install hererocks
    - hererocks lua_install -r^ --$LUA
    - export PATH=$PATH:$PWD/lua_install/bin
    - python -V
    - pip --version
    - pip install -r requirements.txt
  script:
    - python LuatableBot.py
