image: python:3

stages:
  - update

update:
  stage: update
  tags:
    - local
  only:
    - master
  variables:
    LUA: lua=5.3
  before_script:
    - git clone https://github.com/TeamFleet/KCKit.git
    - apt-get update
    - curl -sL https://deb.nodesource.com/setup_9.x | bash -
    - apt-get install -y -qq unzip nodejs
    - pip install hererocks
    - hererocks lua_install -r^ --$LUA
    - export PATH=$PATH:$PWD/lua_install/bin
    - node -v
    - python -V
    - pip --version
    - pip install -r requirements.txt
  script:
    - python LuatableBot.py
