language: python
python:
  - 3.6
env:
  - LUA="lua=5.3"
before_install:
  - sudo apt-get -qq update
  - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node -v
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
install:
  - pip install -r requirements.txt
branches:
  only:
    - master
before_script:
  - git clone https://github.com/TeamFleet/KCKit.git
script:
  - python LuatableBot.py
before_deploy:
  - cp docs/index.html output/index.html
  - cp docs/style.css output/style.css
deploy:
  provider: pages
  name: kcwikizh
  email: dev@kcwiki.moe
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: output
  on:
    branch: master
